use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'OctopusSDK_Example' do
  pod 'OctopusSDK', :path => '../'

  target 'OctopusSDK_Tests' do
    inherit! :search_paths

    
  end
end
