#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "NSObject+OctAddition.h"
#import "NSString+OctAddition.h"
#import "OctAdvertisingDelegate.h"
#import "OctBadgeLogoView.h"
#import "OctBaseViewController.h"
#import "OctCountDownView.h"
#import "OctDotCloseView.h"
#import "OctImageView.h"
#import "OctLandingPageViewController.h"
#import "OctPlayerView.h"
#import "OctRegionClickView.h"
#import "OctSwipeView.h"
#import "OctWebView.h"
#import "UIView+OctAddition.h"
#import "OctAppInfoHelper.h"
#import "OctDeviceInfoHelper.h"
#import "OctGeoHelper.h"
#import "OctUserEnvInfoHelper.h"
#import "OctHTTPRequest.h"
#import "OctAdRequestModel+Builder.h"
#import "OctSDKHTTPRequest.h"
#import "OctHttpRequestType.h"
#import "OctLogHTTPRequest.h"
#import "OctAdRecordModel.h"
#import "OctAdRequestModel.h"
#import "OctAdResponseModel.h"
#import "OctBaseModel.h"
#import "OctDisposeResponseModel.h"
#import "OctConfigureModel.h"
#import "OctManageModel.h"
#import "OctSecureAccessData.h"
#import "OctAdRequestError.h"
#import "OctCore.h"
#import "OctAdViewAttribute.h"
#import "OctBusinessReport.h"
#import "OctEventCodes.h"
#import "OctReplaceURLTools.h"
#import "OctWriteOfflineReport.h"
#import "OctAdvertisingType.h"
#import "OctAdvertLog.h"
#import "NSData+OctAES.h"
#import "OctAdAES.h"
#import "OctAdGTMBase64.h"
#import "OctAdGTMDefines.h"
#import "OctGTMBase64.h"
#import "OctGTMDefines.h"
#import "OctClickWorker.h"
#import "OctDefines.h"
#import "OctDefinitionTools.h"
#import "OctDevice.h"
#import "OctGcdTimer.h"
#import "OctNetworking.h"
#import "OctCompatibilityMacros.h"
#import "OctHTTPSessionManager.h"
#import "OctURLSessionManager.h"
#import "NSArray+OctSafe.h"
#import "NSDictionary+OctSafe.h"
#import "NSTimer+OctTimer.h"
#import "UIView+OctAttribute.h"
#import "UIView+OctFrame.h"
#import "NSData+OctEncryption.h"
#import "NSString+OctEncryption.h"
#import "OctNetworkReachabilityManager.h"
#import "OctSecurityPolicy.h"
#import "OctURLRequestSerialization.h"
#import "OctURLResponseSerialization.h"
#import "OctNetworkStatusTools.h"
#import "OctOtherTools.h"
#import "NSObject+OctModel.h"
#import "OctClassInfo.h"
#import "OctModel.h"
#import "OctResourcesFile.h"
#import "OctResourcesHeader.h"
#import "OctScreenTool.h"
#import "OctSecurityAndGziptTool.h"
#import "OctStaticString.h"
#import "OctTimeTools.h"
#import "OctTools.h"
#import "OctUncaughtExceptionHandler.h"
#import "OctVersionTools.h"
#import "OctWorkerDelegate.h"

FOUNDATION_EXPORT double OctCoreVersionNumber;
FOUNDATION_EXPORT const unsigned char OctCoreVersionString[];

